package main

const (
	CommandTrigger     = "quiz"
	CommandDisplayName = "Quiz commands"
	CommandDescription = "Created by Quiz plugin"

	BotUserName    = "quiz"
	BotDisplayName = "Quiz Bot"
	BotDescription = "Created by the Quiz plugin."

	APIPath = "/api/v1"

	DialogPath                   = "/dialog"
	DialogPathNameQuiz           = "/name"
	DialogPathChangeType         = "/type"
	DialogPathDelete             = "/delete"
	DialogPathAddQuestion        = "/add"
	DialogPathReviewQuestions    = "/review"
	DialogPathRemoveQuestion     = "/remove"
	DialogPathGameStart          = "/start"
	DialogPathScore              = "/score"
	DialogPathAnswer             = "/answer"
	DialogPathNameCourse         = "/nameCourse"
	DialogPathCourseDescription  = "/courseDescription"
	DialogPathCourseDelete       = "/deleteCourse"
	DialogPathAddLesson          = "/addLesson"
	DialogPathEditLesson         = "/editLesson"
	DialogPathNameLesson         = "/nameLesson"
	DialogPathLessonIntroduction = "/lessonIntroduction"
	DialogPathAddResource        = "/addResource"
	DialogPathAddQuizResource    = "/addQuizResource"
	DialogPathRemoveResources    = "/removeResource"
	DialogPathLessonDelete       = "/deleteLesson"

	AttachmentPath                   = "/attachment"
	AttachmentPathNameQuiz           = "/name"
	AttachmentPathChangeType         = "/type"
	AttachmentPathDelete             = "/delete"
	AttachmentPathAddQuestion        = "/add"
	AttachmentPathReviewQuestions    = "/review"
	AttachmentPathRemoveQuestion     = "/remove"
	AttachmentPathSave               = "/save"
	AttachmentPathSelectAnswer       = "/selectAnswer"
	AttachmentPathAnswer             = "/answer"
	AttachmentPathNext               = "/next"
	AttachmentPathScore              = "/score"
	AttachmentPathNameCourse         = "/nameCourse"
	AttachmentPathCourseDelete       = "/deleteCourse"
	AttachmentPathCourseDescription  = "/courseDescription"
	AttachmentPathAddLesson          = "/addLesson"
	AttachmentPathEditLesson         = "/editLesson"
	AttachmentPathSaveCourse         = "/saveCourse"
	AttachmentPathNameLesson         = "/nameLesson"
	AttachmentPathLessonBack         = "/lessonBack"
	AttachmentPathLessonIntroduction = "/lessonIntroduction"
	AttachmentPathAddResource        = "/addResource"
	AttachmentPathAddQuizResource    = "/addQuizResource"
	AttachmentPathRemoveResources    = "/removeResource"
	AttachmentPathLessonDelete       = "/lessonDelete"

	StaticPath = "/static"

	DialogTypeSelect    = "select"
	DialogTypeBool      = "bool"
	DialogTypeText      = "text"
	DialogSubtypeNumber = "number"

	AttachmentContextFieldID          = "ID"
	AttachmentContextFieldCorrect     = "correct"
	AttachmentContextFieldGameID      = "gameID"
	AttachmentContextFieldQuestionID  = "questionID"
	AttachmentContextFieldLessonIndex = "index"

	DialogSubmissionFieldName              = "name"
	DialogSubmissionFieldType              = "type"
	DialogSubmissionFieldQuestion          = "question"
	DialogSubmissionFieldAnswer            = "answer"
	DialogSubmissionFieldWrongAnswer       = "wrong_"
	DialogSubmissionFieldGameQuiz          = "quiz"
	DialogSubmissionFieldGameType          = "type"
	DialogSubmissionFieldGameScoring       = "scoring"
	DialogSubmissionFieldNumberOfQuestions = "nquestions"
	DialogSubmissionFieldGameAnswer        = "game_answer"
	DialogSubmissionFieldDescription       = "description"
	DialogSubmissionFieldLesson            = "lesson"
	DialogSubmissionFieldContent           = "content"
	DialogSubmissionFieldQuiz              = "quiz"

	IncorrectAnswerCount = 3
	Separator            = "-------------"

	AchievementNameContentCreator = "Content creator"
	AchievementNameWinner         = "Winner"
	AchievementNameHardWorker     = "Hard worker"
)
